### ISSUE TITLE
Comment on Community Activitiy Metrics Model

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-metrics-models#48]
Please add any feedback here regarding the Community Activity Metrics Model

**Comment by foundjem** [comment]
I like the direction towards sustainability, however, the following statement could be invalidated if a project reaches Maturity:

> High levels of community activity may indicate that a project is sustainable and low levels of community activity may indicate that a project is at risk.

Also, a community may be receiving a higher volume of fixes or issues reporting without necessarily new features, this condition doesn't suggest sustainability since it lacks changing needs of stakeholders requirements.

**Comment by eyehwan** [comment]
I agree your both  comments. I would like put activity as part of sustainability. So we put it under ecosystem context areas: https://github.com/chaoss/wg-metrics-models/tree/main/context-areas

**Comment by ElizabethN** [comment]
I'm going to go ahead and close this. If there are further comments we can address them at the next meeting, but I think this model is pretty solid now. It can be found here: https://chaoss.community/kb/metrics-model-community-activity/
